source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

workspace 'SSRequstHandler'
project 'SSRequstHandler'

target 'SSRequstHandler' do
    pod 'AFNetworking', '~> 3.0'
    pod 'SSRequstHandler', :path => '../../SSRequstHandler'
    pod 'SwiftyJSON', '5.0.0'
end
