source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

workspace 'SSRequstHandlerDemo'
project 'SSRequstHandlerDemo'

target 'SSRequstHandlerDemo' do
    pod 'AFNetworking', '~> 3.0'
    pod 'SSRequstHandler', :path => '../../SSRequstHandler'
end
